# Generated by Django 4.2.4 on 2023-08-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UniversalEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xname', models.CharField(max_length=100)),
                ('xdescription', models.TextField(blank=True)),
                ('xcode', models.CharField(blank=True, max_length=20)),
                ('xlatitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('xlongitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('xcreated_at', models.DateTimeField(auto_now_add=True)),
                ('xupdated_at', models.DateTimeField(auto_now=True)),
                ('xtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_manager.type')),
            ],
        ),
    ]
