# Generated by Django 4.2.4 on 2023-08-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='universalentities',
            unique_together={('xtype', 'xname')},
        ),
    ]
