# Generated by Django 4.2.4 on 2023-09-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity_manager', '0004_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
