# Generated by Django 4.2.4 on 2023-09-14 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity_manager', '0008_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity_manager.business'),
        ),
    ]
